name: CommandLogger
main: ir.muvixo.cmdlogger.bungee.CommandLogger
version: ${project.version}
author: muvixo
description: Forwards every command executed by players to BungeeCord staff

commands:
  logs:
    description: CommandLogger main command
    usage: /clogs help
    aliases: [vlogs, commandlogger, cmdlogs, commandlogs]
