# ============================================================
#  CommandLogger-Paper v2.2 - backend config
#  Created by Muvixo
# ============================================================

channel: "commandlogger:main"

server-name: ""

log-ops: true

report-op-status: true

op-status-interval-minutes: 1

blacklist:
  - "login"
  - "register"
  - "changepassword"

ignored-players: []

permissions:
  use:      "commandlogger.use"
  creator:  "commandlogger.creator"

  admin:    "commandlogger.admin"
  reload:   "commandlogger.reload"
  status:   "commandlogger.status"
  toggle:   "commandlogger.toggle"
  debug:    "commandlogger.debug"
